apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-backend-rest-app
  template:
    metadata:
      labels:
        app: my-backend-rest-app
    spec:
      containers:
        - name: kubenginx
          image: stacksimplify/kube-helloworld:1.0.0
          ports:
            - containerPort: 8080
