apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend-nginx-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-frontend-nginx-app
  template:
    metadata:
      labels:
        app: my-frontend-nginx-app
    spec:
      containers:
        - name: kubenginx
          image: stacksimplify/kube-frontend-nginx:1.0.0
          ports:
            - containerPort: 80
