apiVersion: v1
kind: Service
metadata:
  name: my-helloworld-deployment-service
spec:
  selector:
    app: my-first-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
